server.port: 5601
server.host: "0.0.0.0"
# elasticsearch.hosts: ["http://localhost:9200"]
pid.file: /run/kibana/kibana.pid
logging:
  appenders:
    file:
      type: file
      fileName: /var/log/kibana/kibana.log
      layout:
        type: json
  root:
    appenders:
      - default
      - file
