global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - '192.168.56.102:9100'  # nginx
          - '192.168.56.103:9100'  # apache1
          - '192.168.56.104:9100'  # apache2
