global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - '192.168.68.53:9100'  # nginx
          - '192.168.68.55:9100'  # apache1
          - '192.168.68.57:9100'  # apache2
